version: '3'

env:
  PYTHON_VER: 3.11
  CARDANO_NODE_VERSION: 8.1.2
  CARDANO_SUBMIT_API_VERSION: 8.1.2
  NETWORK: mainnet
  # NETWORK: testnet

tasks:
  hello:
    cmds:
      - echo 'Hello World from Task!'
    silent: true

  run_podman_compose:
    cmds:
      - podman-compose up

  install_podman_compose:
    cmds:
      - task: install_python
      # FIX BUG PODMAN
      - jq '.cniVersion = "0.4.0"'  ~/.config/cni/net.d/cardano-node_default.conflist > tmp_file.json && mv tmp_file.json  ~/.config/cni/net.d/cardano-node_default.conflist
      - task: install_podman
      - task: install_jq
      - task: pull_container_cardano
      - podman volume create cardano_node-db
      - podman volume create cardano_node-ipc
      - podman network create cardano_default 

  pull_container_cardano:
    cmds:
      - podman pull docker://inputoutput/cardano-node:$CARDANO_NODE_VERSION
      - podman pull docker://inputoutput/cardano-submit-api:$CARDANO_NODE_VERSION

  install_jq:
    cmds:
      - sudo apt install -y jq

  install_podman:
    cmds:
      - sudo apt install -y podman
      - pip$PYTHON_VER install podman-compose
      - podman run hello-world

  install_python:
    cmds:
      - sudo apt -y update 
      - sudo apt -y upgrade
      - sudo apt -y install software-properties-common
      - sudo add-apt-repository -y ppa:deadsnakes/ppa
      - sudo apt -y update
      - sudo apt install python$PYTHON_VER
      - curl -sS https://bootstrap.pypa.io/get-pip.py | python$PYTHON_VER

